title:               The Coffee Shop Table
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']

# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             'https://cst.ineedmore.coffee'

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at # Allows for the git-based "last modified dates"
  - jekyll-sitemap # Creates a sitemap for search engine indexing
  - jekyll-toc # Allows easy addition of a table of contents

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  # By default, all files will be displayed with the default layout if unspecified
  - scope:
      path: "**/*"
    values:
      layout: "default"
  # By default, all files in _notes should have the note layout
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  # By default, all png files shouldn't be included in the sitemap
  - scope:
      path: "assets/**/*.png"
    values:
      sitemap: false
  # By default, all pdf files shouldn't be included in the sitemap
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
